import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font";

import "@/app/globals.css";
import NavBar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`${GeistSans.variable} ${GeistMono.variable}`}>
        <NavBar />
        <div className="max-w-3xl mx-6 xl:mx-auto py-16 lg:py-32">
          <article className="prose lg:prose-xl prose-gray prose-invert">
            {children}
          </article>
        </div>
      </body>
    </html>
  );
}
